import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { CartDetailsProvider } from "@/context/cart";
import PromotionsHeader from "@/components/promotionsHeader";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FlipMart - Buy products online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartDetailsProvider>
          <PromotionsHeader />
          <Header />
          <main className="min-h-[80vh] w-[90%] max-w-5xl mx-auto">
            {children}
          </main>
          <Footer />
        </CartDetailsProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
